"""Frontend-only tools, generated with the site's shared page wrapper."""
from pathlib import Path

TOOLS = [
    ('golf-trip-planner', 'Golf Trip Planner', 'The trip that finally leaves the group chat.', 'Tee times, travel, and the little details. Put your next great golf trip in order.', 'badge-coastal.png', 'Plan the trip'),
    ('golf-trip-budget-calculator', 'Golf Trip Budget Calculator', 'More great rounds. Fewer surprises.', 'Know the cost before anyone commits. Compare the extras and see what your group needs to budget.', 'badge-fairway.png', 'Build the budget'),
    ('golf-daylight-calculator', 'Can I Finish Before Dark?', 'One more round. Enough daylight?', 'Find your latest tee time for 9 or 18 holes, with room for the pace of real golf.', 'badge-sunrise.png', 'Check the daylight'),
    ('golf-membership-calculator', 'Golf Membership Break-Even Calculator', 'You play a lot. Make it count.', 'Find the rounds it takes to make a golf membership worthwhile, including the costs beyond dues.', 'badge-golfer.png', 'Run the numbers'),
    ('golf-swing-analyzer', 'Swingalysis by Greenskeeper', 'Your swing. A closer look.', 'Review every frame, draw what matters, and compare two swings. Free, private, and right in your browser.', 'badge-eagle.png', 'Review your swing'),
]

def field(label, name, value='', kind='text', extra='', hint=''):
    return f'<label class="field"><span>{label}</span><input name="{name}" type="{kind}" value="{value}" {extra}>{f"<small>{hint}</small>" if hint else ""}</label>'

def select(label, name, options, value=''):
    return f'<label class="field"><span>{label}</span><select name="{name}">'+''.join(f'<option value="{v}" {"selected" if v == value else ""}>{t}</option>' for v,t in options)+'</select></label>'

def panel(title, text, content, step='01'):
    return f'<section class="tool-panel"><div class="panel-heading"><span class="step-number">{step}</span><div><h2>{title}</h2><p>{text}</p></div></div>{content}</section>'

def cards(prefix='../', exclude=''):
    return ''.join(f'<a class="tool-card" href="{prefix}{slug}/"><div class="tool-card-art"><img src="{prefix}../images/{badge}" alt="" width="130" height="130" loading="lazy"><span class="tool-number">0{i+1} / FREE TOOL</span></div><div class="tool-card-copy"><h3>{title}</h3><p>{desc}</p><span class="text-link">{action} ↗</span></div></a>' for i,(slug,title,headline,desc,badge,action) in enumerate(TOOLS) if slug != exclude)

def planner():
    overview = '<div class="fields two">'+field('Trip name', 'name', 'The next great golf trip', extra='maxlength="100" required')+field('Golfers', 'golfers', '8', 'number', 'min="1" max="100" required')+field('Arrival', 'start', '', 'date', 'required')+field('Return', 'end', '', 'date', 'required')+field('Trip timezone', 'zone', 'America/Denver', extra='required list="timezones"', hint='All itinerary times use this timezone.')+'</div>'
    add = '<form id="event-form"><div class="fields two">'+field('Course or activity', 'eventName', '', extra='placeholder="A course worth the detour" maxlength="140" required')+select('Activity', 'eventType', [(x,x) for x in ['Golf','Travel','Stay','Meal','Other']])+field('Date', 'eventDate', '', 'date', 'required')+field('Start time', 'eventTime', '09:00', 'time', 'required')+field('Duration (minutes)', 'eventDuration', '270', 'number', 'min="5" max="1440" required')+field('Travel buffer after (minutes)', 'eventBuffer', '30', 'number', 'min="0" max="240" required')+'</div><label class="field"><span>Notes / booking details</span><textarea name="eventNote" maxlength="500" rows="2" placeholder="Confirmation number, who booked, or where to meet"></textarea></label><label class="check"><input name="eventConfirmed" type="checkbox"> Booking confirmed</label><button class="button" type="submit">Add to itinerary <span aria-hidden="true">↗</span></button></form>'
    return '<div class="tool-workspace"><div class="tool-inputs"><form id="trip-form">'+panel('Make it a trip', 'Start with the essentials. Everything stays in this browser.', overview)+'</form>'+panel('Add a round. Or a detour.', 'Use the travel buffer to leave room between plans.', add, '02')+'<div class="quiet-actions"><button type="button" class="text-button" id="sample-trip">Load an example trip</button><button type="button" class="text-button" id="import-trip">Open a trip file</button><input type="file" id="trip-file" accept=".json,application/json" hidden><button type="button" class="text-button" id="clear-trip">Start fresh</button></div><p class="fine" id="save-status">Saved in this browser. Download a trip file for a portable backup.</p></div><aside class="tool-result itinerary-result" aria-label="Your itinerary"><div class="result-top"><span class="eyebrow">YOUR NEXT GREAT TRIP</span><span class="result-chip" id="trip-count">0 activities</span></div><h2 id="trip-title">The next great golf trip</h2><p id="trip-summary"></p><div id="itinerary"></div><div class="export-actions"><button class="button small" id="copy-trip">Copy itinerary</button><button class="secondary-button" id="calendar-trip">Add to calendar</button><button class="secondary-button" id="download-trip">Download trip file</button><button class="text-button" data-print>Print / save PDF</button></div><p class="fine">Proposed times are plans, not reservations. Calendar files contain your scheduled activities.</p></aside></div>'

def budget():
    basics = '<form id="budget-form"><div class="fields three">'+field('Golfers', 'golfers', '8', 'number', 'min="1" max="100" required')+field('Nights', 'nights', '3', 'number', 'min="0" max="60" required')+select('Currency', 'currency', [(x,x) for x in ['USD','GBP','EUR','CAD','AUD']], 'USD')+'</div></form><p class="fine">Amounts are your quotes or estimates. Use one currency per trip. Enter 0 nights for a day trip.</p><button class="text-button" id="use-trip" type="button" hidden>Use the group from my saved trip ↗</button>'
    return '<div class="tool-workspace"><div class="tool-inputs">'+panel('Who’s coming?', 'Make the numbers work for your actual group.', basics)+panel('The whole picture', 'Choose whether each price is a total, per person, or per night.', '<div id="expense-list"></div><button class="secondary-button" id="add-expense">+ Add a cost</button>', '02')+'<div class="quiet-actions"><button class="text-button" id="reset-budget">Reset budget</button></div></div><aside class="tool-result" aria-label="Your trip budget"><span class="eyebrow">THE TRIP, IN NUMBERS</span><p class="metric-label">Group total</p><div class="hero-metric" id="budget-total">$0</div><div class="result-stats"><div><span>Average per golfer</span><strong id="budget-person">$0</strong></div><div><span>Golfers · nights</span><strong id="budget-group">8 · 3</strong></div></div><p id="budget-unknown" class="result-note"></p><div class="cost-breakdown" id="budget-breakdown"></div><p class="fine">The per-golfer figure is a group average. Each cost shows its split among the people sharing it. Deposits are part of the cost, not additional expenses.</p><details class="scenario"><summary>What if someone drops out?</summary><p id="budget-scenario"></p><p class="fine">Shared totals stay fixed; per-person charges scale. Assumes one fewer person shares every cost they participated in. Check cancellation terms.</p></details><div class="export-actions"><button class="button small" id="copy-budget">Copy budget</button><button class="text-button" data-print>Print / save PDF</button></div><p id="budget-save" class="fine">Budget autosaves in this browser.</p></aside></div>'

def daylight():
    cities = [('denver','Denver, Colorado'),('scottsdale','Scottsdale, Arizona'),('myrtle','Myrtle Beach, South Carolina'),('sandiego','San Diego, California'),('palmsprings','Palm Springs, California'),('traverse','Traverse City, Michigan'),('standrews','St Andrews, Scotland'),('dublin','Dublin, Ireland'),('melbourne','Melbourne, Australia'),('custom','Custom course location')]
    inputs = '<form id="daylight-form">'+select('Course area', 'place', cities, 'denver')+'<div class="fields two">'+field('Round date', 'date', '', 'date', 'required')+field('Tee time', 'tee', '14:00', 'time', 'required')+'</div><fieldset class="segmented"><legend>How many holes?</legend><label><input type="radio" name="holes" value="18" checked><span>18 holes</span></label><label><input type="radio" name="holes" value="9"><span>9 holes</span></label></fieldset><div class="fields two">'+field('Expected round (minutes)', 'duration', '270', 'number', 'min="30" max="720" required', '270 min = 4 hr 30 min. Include likely delays.')+field('Finish before sunset (minutes)', 'buffer', '30', 'number', 'min="0" max="180" required', 'Leave room for shade, cloud, and finding your ball.')+'</div><details id="location-details"><summary>Use exact course coordinates</summary><p>Presets use city centers. For a closer estimate, enter your course coordinates and timezone.</p><div class="fields two">'+field('Latitude', 'lat', '39.7392', 'number', 'step="any" min="-89.9" max="89.9" required')+field('Longitude', 'lng', '-104.9903', 'number', 'step="any" min="-180" max="180" required')+field('Course timezone', 'zone', 'America/Denver', extra='list="timezones" required')+'</div><button type="button" class="secondary-button" id="locate-course">Use my location</button><p class="fine">Only if you’re at the course. Coordinates stay here; confirm the course timezone.</p></details><button class="button" type="submit">Check my round <span aria-hidden="true">↗</span></button></form>'
    return '<div class="tool-workspace"><div class="tool-inputs">'+panel('Is there time for one more?', 'Choose the course location, not your home timezone.', inputs)+'<p class="fine">Sunset is estimated with <a href="https://gml.noaa.gov/grad/solcalc/calcdetails.html" class="source-link">NOAA solar equations</a>. Weather, hills, trees, and course closing times can shorten usable light.</p></div><aside class="tool-result daylight-result" aria-label="Your golf daylight estimate"><span class="eyebrow">THE LAST GOOD LIGHT</span><p class="metric-label">Latest suggested tee time</p><div class="hero-metric" id="daylight-latest">—</div><p class="result-note" id="daylight-verdict">Choose your round to check the light.</p><div class="daylight-landscape" aria-hidden="true"><img src="../../images/badge-sunrise.png" alt="" width="160" height="160"><div class="daylight-track"><span id="daylight-marker"></span></div></div><div class="result-stats"><div><span>Your estimated finish</span><strong id="daylight-finish">—</strong></div><div><span>Estimated sunset</span><strong id="daylight-sunset">—</strong></div></div><p id="daylight-context" class="fine"></p><div class="export-actions"><button class="button small" id="copy-daylight">Copy round estimate</button></div><p class="fine">Plan around sunset, rather than assuming twilight is playable. Confirm the course’s last tee time and cart-return deadline.</p></aside></div>'

def membership():
    inputs = '<form id="membership-form"><div class="fields two">'+select('Currency', 'currency', [(x,x) for x in ['USD','GBP','EUR','CAD','AUD']], 'USD')+field('Rounds per year', 'rounds', '104', 'number', 'min="1" max="1000" required', 'Twice a week ≈ 104. Three times ≈ 156.')+field('Annual membership dues', 'annual', '3500', 'number', 'min="0" max="100000000" step="0.01" required')+field('Joining fee (first year)', 'joining', '500', 'number', 'min="0" max="100000000" step="0.01" required')+field('Monthly fees / minimum', 'monthly', '50', 'number', 'min="0" max="100000000" step="0.01" required', 'Include spending you wouldn’t otherwise make.')+field('Pay-as-you-play cost / round', 'publicCost', '85', 'number', 'min="0" max="100000000" step="0.01" required', 'Green fee + cart + usual extras.')+field('Member cost / round', 'memberCost', '20', 'number', 'min="0" max="100000000" step="0.01" required', 'Include cart, guest fees, or other round charges.')+'</div><button class="button" type="submit">Compare my options <span aria-hidden="true">↗</span></button></form>'
    return '<div class="tool-workspace"><div class="tool-inputs">'+panel('For the golfer who keeps going back', 'Example numbers to get you started. Replace them with your course’s actual costs.', inputs)+'<details class="assumptions"><summary>What should I include?</summary><p>Include taxes in the amounts you enter. Treat refundable deposits separately. Monthly minimums should reflect additional spending you would not make anyway. This comparison assumes every entered round is played at the member rate; reduce your round count if you often travel or play elsewhere.</p><p>Tee-time access, course quality, practice facilities, and guest privileges also matter. They aren’t assigned an invented dollar value here.</p></details></div><aside class="tool-result" aria-label="Your membership comparison"><span class="eyebrow">YOUR REPEAT VISITS, RECONSIDERED</span><p class="metric-label">First-year break-even</p><div class="hero-metric" id="membership-break">—</div><p class="result-note" id="membership-verdict"></p><div class="result-stats"><div><span>Later-year break-even</span><strong id="membership-ongoing-break">—</strong></div><div><span>Planned rounds / week</span><strong id="membership-weekly">—</strong></div></div><div class="comparison-bars" id="membership-bars"></div><p id="membership-context" class="fine"></p><div class="export-actions"><button class="button small" id="copy-membership">Copy comparison</button><button class="text-button" data-print>Print / save PDF</button></div></aside></div>'

def swing():
    return '<div class="swing-feature"><div class="swing-preview"><img src="../../images/swingalysis-preview.png" width="900" height="600" alt="Swingalysis swing review preview showing a golfer at address"><span class="preview-caption">A closer look at the swing you already have.</span></div><div class="swing-intro"><span class="eyebrow">SWINGALYSIS BY GREENSKEEPER</span><h2>Less guessing.<br>More seeing.</h2><p>Open a swing video from your device. Scrub frame by frame, draw reference lines and angles, then compare two swings side by side or overlaid.</p><a class="button" href="https://swingalysis.com/analyze?source=greenskeeper">Open Swingalysis <span aria-hidden="true">↗</span></a><a class="text-link" href="https://swingalysis.com/analyze?demo=1&amp;source=greenskeeper">Try the demo first ↗</a><p class="fine">Free. No account. Videos stay in your browser.</p></div></div><div class="swing-capabilities"><article><span class="step-number">01</span><h3>Find the frame.</h3><p>Slow down, step through the motion, and come back to the moment you want to understand.</p></article><article><span class="step-number">02</span><h3>Make your marks.</h3><p>Draw lines, angles, and paths yourself. Visual references, without invented swing scores.</p></article><article><span class="step-number">03</span><h3>Keep the evidence.</h3><p>Download annotated screenshots or videos for your own review or a conversation with your coach.</p></article></div><p class="swing-footnote">Swingalysis is a manual video-review workspace. It does not calculate club speed, ball flight, or automatic biomechanical diagnoses. Saved project files contain settings and drawings; reopen your original videos when returning.</p>'

def build_tools(output, root, config, page):
    hub = '<section class="wrap tools-hub"><header class="tools-hub-head"><div><span class="eyebrow">FOR THE LOVE OF THE GAME · FIVE FREE TOOLS</span><h1>More golf.<br><span>Less figuring it out.</span></h1><p>For the next buddies trip. The late-afternoon nine. The course you keep coming back to. Useful tools for a life with more golf in it.</p><div class="tool-promises"><span>No account needed</span><span>Free to use</span><span>Built for golfers</span></div></div><div class="hub-badges" aria-hidden="true"><img src="../images/badge-coastal.png" class="hub-badge-one" width="230" height="230" alt=""><img src="../images/badge-sunrise.png" class="hub-badge-two" width="190" height="190" alt=""><img src="../images/badge-golfer.png" class="hub-badge-three" width="145" height="145" alt=""></div></header><div class="tools-grid">'+cards(prefix='')+'</div>'+cta(config, '../')+'</section>'
    (output/'tools').mkdir(exist_ok=True)
    (output/'tools/index.html').write_text(add_assets(page('Free Golf Tools | Greenskeeper', 'Five free tools for golf trips, budgets, daylight, membership costs, and swing review.', hub, config, 'tools/', '../'), '../'))
    bodies = [planner(), budget(), daylight(), membership(), swing()]
    for (slug,title,headline,desc,badge,action), body in zip(TOOLS,bodies):
        intro = f'<section class="wrap tool-page" data-tool="{slug}"><a class="back-link" href="../">← All free tools</a><header class="tool-heading"><div><span class="eyebrow">FREE GOLF TOOLS / {title.upper()}</span><h1>{headline}</h1><p>{desc}</p></div><img src="../../images/{badge}" alt="" width="124" height="124"></header><noscript><p class="editor-note">Enable JavaScript to use this interactive tool. Swingalysis opens in its own browser workspace.</p></noscript><p id="tool-error" role="alert" class="tool-error" hidden></p><p id="tool-status" class="tool-toast" role="status" aria-live="polite" hidden></p>{body}<datalist id="timezones">'+''.join(f'<option value="{z}">' for z in ['America/Denver','America/Phoenix','America/New_York','America/Los_Angeles','America/Chicago','Europe/London','Europe/Dublin','Australia/Melbourne'])+'</datalist>'+cta(config, '../../')+'<section class="more-tools"><div class="section-heading"><h2>A little more golf.</h2><a class="text-link" href="../">Explore all five tools ↗</a></div><div class="tools-grid compact">'+cards(exclude=slug)+'</div></section></section>'
        folder = output/'tools'/slug; folder.mkdir(exist_ok=True)
        (folder/'index.html').write_text(add_assets(page(title+' | Greenskeeper', desc, intro, config, f'tools/{slug}/', '../../'), '../../', interactive=True))

def cta(config, prefix):
    return f'<aside class="tools-app-cta"><img src="{prefix}images/greenskeeper-logo.png" width="54" height="54" alt=""><div><span class="eyebrow">FROM SOMEDAY TO PLAYED IT</span><h2>Keep the places.<br>Keep the feeling.</h2><p>Your played courses, your next-trip bucket list, and the memories in between. Together in Greenskeeper for iPhone.</p></div><a class="button" href="{config["app_store_url"]}">Get Greenskeeper ↗</a></aside>'

def add_assets(html, prefix, interactive=False):
    assets = f'<link rel="stylesheet" href="{prefix}assets/tools.css">'
    if interactive: assets += f'<script defer src="{prefix}assets/tools-core.js"></script><script defer src="{prefix}assets/tools.js"></script>'
    return html.replace('</head>', assets+'</head>')
